Speler user input
RickWinters/Stratego_project pull request #15
Opened 2019-05-04 16:34 UTC by RickWinters

2019-05-05 11:41 UTC, HorstMF commented on src/nl/Stratego/Bord.java
> +                System.out.println("het gekozen speelstuk is niet van jou team");
"het gekozen speelstuk is niet van jouw team"  
je bent de 'w' vergeten achter jou hihi

2019-05-05 11:53 UTC, HorstMF approved these changes
Holy, mooi gedaan hoor! Complimenten 👍

2019-05-05 18:15 UTC, FernonE requested changes
Ziet er mooi uit! Werkte ook netjes dus ben tevreden hierover :D
Voor de volledigheid staat er nog een functie in die je herschreven hebt: checkValidPiece ipv pieceCheck. Ik zou dus voor mergen eerst pieceCheck verwijderen.

2019-05-05 18:15 UTC, FernonE commented on src/nl/Stratego/Speler.java
> +        try{
Waarom niet coords initialiseren met {-1,-1} en dan: if(first == integer && second == integer) {....}
Dan hoef je niet met een exception te werken. En wordt het ook leesbaarder van.

Daarnaast is deze exception algemeen en heb ik geen idee welk exception je hier verwacht. Is het als je een string intypt, is het out of bounds. Ik zou gewoon proberen geen exception te gebruiken hiervoor.

2019-05-05 18:15 UTC, FernonE commented on src/nl/Stratego/Speler.java
> +        do{
Hier hoeft in principe geen do while loop. Je gebruikt passed = false; waardoor je while loop sws al 1 keer gaat lopen. 
Als je die regel boolean passed = false; weghaalt dan is het wel nodig :D. Maar beide hoeft niet.

2019-05-05 18:15 UTC, FernonE commented on src/nl/Stratego/Speler.java
> +    private boolean checkPiece(int[] coords,Bord bord){
een functie zonder enig nut er staat niks in.

2019-05-05 18:15 UTC, FernonE commented on src/nl/Stratego/Speler.java
> +            if(!this.checkPiece(selectCoords,bord)){ //daarna kijken of het wel een correcte speelstuk is
Omdat dit die methode aanroept die niks doet zou ik dit vervangen door:
if(!bord.checkValidPiece(selectCoords[1],selectCoords[0],this.spelerTeam))

doet hetzelfde en dan kan die functie weg

2019-05-05 18:15 UTC, FernonE commented on src/nl/Stratego/Bord.java
> +            if (gekozenSpeelStuk.getTeam() != team){
if (   ((speelstuk)gekozenStuk).getTeam() != team){...}
Dit had ik toen in de chat aan raymond gevraagd en dit zou moeten werken. Weer een variabele minder voor de G.C. om op te ruimen :p

2019-05-06 13:21 UTC, FernonE commented on src/nl/Stratego/Speler.java
> +        try{
```suggestion
   int[] coords = new int[]{-1,-1};
   coords[0] = Integer.parseInt(first)-1;
   coords[1] = Integer.parseInt(second)-1;     
    if(first == integer && second == integer){
            coords[0] = Integer.parseInt(first)-1;
            coords[1] = Integer.parseInt(second)-1;
            }
   
```

2019-05-06 13:43 UTC, merged